version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt

  build:
    commands:
      - echo Build phase complete.

artifacts:
  files:
    - '**/*'
    - appspec.yml              # importante para CodeDeploy
    - scripts/**               # scripts de inicio/parada
  discard-paths: no
